### ISSUE TITLE
Make a Casdoor Flutter SDK like other languages

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-flutter-sdk#1]
See other languages: https://github.com/casdoor?q=sdk&type=all&language=&sort=

This SDK will be used by Flutter apps to connect to Casdoor authentication platform.

**Comment by hsluoyz** [comment]
@Rishabhmodii

/cc @MrUnfunny

**Comment by MrUnfunny** [comment]
@Rishabhmodii let's discuss this. Go through [casdoor-node-js](https://github.com/casdoor/casdoor-nodejs-sdk) and hit me up after this.

**Comment by hsluoyz** [comment]
@Rishabhmodii
