### ISSUE TITLE
Not works on Flutter Web release

### ISSUE THREAD

**Issue by pyxiscloud** [casdoor/casdoor-flutter-sdk#18]
Hello,
I've build release for Web and got this error in Chrome:
`Uncaught MissingPluginException(No implementation found for method authenticate on channel casdoor_flutter_sdk)
`

At development stage thats ok, but release is broken

**Comment by hsluoyz** [comment]
@caoshengdong PTAL

**Comment by caoshengdong** [comment]
@pyxiscloud Cloud you please try this: clear Flutter with `flutter clean`, delete pubspec.lock, and Invalidate and Restard Android Studio, `flutter pub get` to restore packages.

**Comment by pyxiscloud** [comment]
Wow it works!
Thank you!
