### ISSUE TITLE
Problem with refreshToken method

### ISSUE THREAD

**Issue by Deltenman** [casdoor/casdoor-flutter-sdk#28]
When I try to refresh token with method

```
  Future<http.Response> refreshToken(String refreshToken, String? clientSecret,
      {String scope = "read"}) async {
    return await http.post(
        Uri(
          scheme: parseScheme(),
          host: parseHost(),
          port: parsePort(),
          path: "api/login/oauth/refresh_token",
        ),
        body: {
          'grant_type': 'authorization_code',
          'refresh_token': refreshToken,
          'scope': scope,
          'client_id': config.clientId,
          'client_secret': clientSecret
        });
  }
```
, I never get answer with the new token. Tried with/without clientSecret, tried with access/refresh/auth tokens (because thought that have incorrect variable for token) -- no luck. But if I try to do this request manually

    final response = await http.post(
        Uri(
          scheme: "https",
          host: dotenv.get('CASDOOR_ENDPOINT').split("//").last,
          port: 443,
          path: "api/login/oauth/refresh_token",
        ),
        body: {
          'grant_type': 'refresh_token',
          'refresh_token': data.token.refreshToken,
          'scope': "read",
          'client_id': dotenv.get('CASDOOR_CLIENT_ID'),
          'client_secret': dotenv.get('CASDOOR_CLIENT_SECRET'),
        });
, I get the new token. What problem could be in library's method?

**Comment by hsluoyz** [comment]
@Deltenman what's the difference between the two requests? What's the key point you want to specify here?

**Comment by Deltenman** [comment]
@hsluoyz difference in scheme, host and port, I guess, because in my case they was strict, in your method you using parse and config, and it could be...flexible?

**Comment by Deltenman** [comment]
@hsluoyz another grand_type: I using 'grant_type': 'refresh_token', in your method it's 'grant_type': 'authorization_code',

**Comment by hsluoyz** [comment]
@Deltenman can you make a PR to fix it?

**Comment by fischermario** [comment]
@hsluoyz Sorry to barge in here. I'm also interested in the `refreshToken` method. If the app is an Android/iOS app it is a pretty bad idea to put the `client_secret` into the code as it can be easily retrieved by decompiling the app. Is there any other way to obtain a refresh token using the SDK that does not involve supplying the client secret?

**Comment by Deltenman** [comment]
@hsluoyz https://github.com/casdoor/casdoor-flutter-sdk/pull/31
