### ISSUE TITLE
refreshToken for mobile app

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor-flutter-sdk#30]
I'm interested in the `refreshToken` method. If the app is an Android/iOS app it is a pretty bad idea to put the `client_secret` into the code as it can be easily retrieved by decompiling the app.

Is there any other way to obtain a refresh token using the SDK that does not involve supplying the client secret?

**Comment by hsluoyz** [comment]
@fischermario use OAuth PKCE flow, refer to:

- https://github.com/casdoor/casdoor-react-only-example/pull/2#discussion_r1335160457
- https://github.com/casdoor/casdoor-react-native-sdk/commit/a75a9012b207ef7e90d17629c6a506cfee18965e
