### ISSUE TITLE
Upload to pub.dev failed

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor-flutter-sdk#36]
An error occurred while uploading the new release triggered by #35 to pub.dev.

![image](https://github.com/casdoor/casdoor-flutter-sdk/assets/10214295/3970c483-1a16-48f8-92d4-ebb42b8d0b19)

@hsluoyz Can you look into it?

**Comment by hsluoyz** [comment]
@fischermario CI publish has issue. Already manually published: https://pub.dev/packages/casdoor_flutter_sdk

![image](https://github.com/casdoor/casdoor-flutter-sdk/assets/3787410/2593d066-c1c8-4cd1-b303-c9e5d197e253)
