### ISSUE TITLE
Please update http dependency

### ISSUE THREAD

**Issue by pyxiscloud** [casdoor/casdoor-flutter-sdk#39]
Hi,
In my project with casdoor SDK, can't update http package version:
`Because casdoor_flutter_sdk 1.5.0 depends on http >=0.13.4 <1.0.0 and no versions of casdoor_flutter_sdk match >1.5.0 <2.0.0, casdoor_flutter_sdk ^1.5.0 requires http >=0.13.4 <1.0.0.
So, because flutterweb depends on both http ^1.2.1 and casdoor_flutter_sdk ^1.5.0, version solving failed.`
Please use newer version of http?
Thank you

**Comment by hsluoyz** [comment]
@pyxiscloud hi, can you make a PR?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-flutter-sdk/pull/42
