### ISSUE TITLE
Semantic-release should also create GitHub Releases besides the pub.dev package release

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-flutter-sdk#9]
![image](https://user-images.githubusercontent.com/3787410/181047886-16e9f4da-0b57-4cf6-a013-e0ed96a7a660.png)

**Comment by hsluoyz** [comment]
@ziliangyu

**Comment by ziliangyu** [comment]
Yes, I have. It also needs to configure `GITHUB_TOKEN` and `CREDENTIAL_JSON`.
![{1M$NDSAO}EUW)11O$0)AP2](https://user-images.githubusercontent.com/53009950/181511556-ba8e1df4-6cbd-4a0c-a72e-772a404f4362.png)
